title: 市北内卷合作社
description: 存放各种各样的文档！
theme: just-the-docs

url: https://liubanlaobanzhang.github.io/study-together-docs

aux_links:
  帮助编辑此文档库: https://github.com/liubanlaobanzhang/study-together-docs

markdown: kramdown

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
