title: 市北内卷合作社
description: 存放各种各样的文档！
theme: just-the-docs

url: https://liubanlaobanzhang.github.io/study-together-docs

plugins:
  - kramdown

callouts_level: quiet
callouts:
  highlight:
    color: yellow
  important:
    title: 信息
    color: blue
  new:
    title: 信息
    color: green
  note:
    title: 信息
    color: purple
  warning:
    title: 警告
    color: red
  # 以下为新加
  yellow:
    title: 注意
    color: yellow
  blue:
    title: 公告
    color: blue
  green:
    title: 公告
    color: green
  purple:
    title: 信息
    color: purple
  red:
    title: 注意
    color: red
  # 以下无标题
  yellowa:
    color: yellow
  bluea:
    color: blue
  greena:
    color: green
  purplea:
    color: purple
  reda:
    color: red

back_to_top: true
back_to_top_text: "回到顶部"

# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "在 Github 上编辑此文档"
gh_edit_repository: "https://github.com/liubanlaobanzhang/study-together-docs" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
# gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

footer_content: ""
# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: light
