name: 停运服务器

on:
  push:
    branches: ["main"]
    paths:
      - '**.stop-running'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  Change-To-Build-Mod-A: # 进入维护模式
    runs-on: ubuntu-latest
    steps:
      - name: 获取 Failed 界面
        uses: actions/checkout@v3
        with:
          ref: 'Failed'
      - name: 安装 Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1' # Not needed with a .ruby-version file
          bundler-cache: false # runs 'bundle install' and caches installed gems automatically
          cache-version: 0 # Increment this number if you need to re-download cached gems
      - name: 安装 Pages 服务
        id: pages
        uses: actions/configure-pages@v3
      - name: 使用 Jekyll 部署
        run: |
          bundle install
          bundle exec jekyll build --trace --baseurl "${{ steps.pages.outputs.base_path }}"
        env:
          JEKYLL_ENV: production
      - name: 上传部署产物（维护页面）
        uses: actions/upload-pages-artifact@v1

  Change-To-Build-Mod:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: Change-To-Build-Mod-A
    steps:
      - name: 部署维护页面
        id: deployment
        uses: actions/deploy-pages@v2